version: "2.0"
services:
   scrapyd:
     build: .
     image: scrapyd
     restart: always
     volumes:
       - .:/opt
     environment:
       - TZ=Asia/Shanghai
   nginx:
     build: ./nginx
     restart: always
     ports:
       - "6886:6801"
     links:
       - "scrapyd:scrapyd"
     environment:
       - TZ=Asia/Shanghai